ServerName localhost

LoadModule cgid_module /usr/lib/apache2/modules/mod_cgid.so

ScriptAlias /api /usr/lib/cgi-bin/soeder-api
<Directory "/usr/lib/cgi-bin">
    Options +ExecCGI
    Require all granted
</Directory>

DocumentRoot /var/www/html
<Directory "/var/www/html">
    Options -Indexes +FollowSymLinks
    AllowOverride None
    Require all granted
    FallbackResource /index.html
</Directory>
